In [1]:
import numpy as np

In [18]:
my_list = [2,6,2,8,4,0,1,5,7]
my_arr = np.array(my_list)
my_arr = my_arr.reshape(3,3)

In [19]:
my_arr

array([[2, 6, 2],
       [8, 4, 0],
       [1, 5, 7]])

In [27]:
calculations = {
      # mean
      'mean': [
      my_arr.mean(axis=0, dtype=np.float64), my_arr.mean(axis=1, dtype=np.float64), my_arr.mean(dtype=np.float64)
      # np.mean(my_arr, axis=0)  
      ],
      # variance
      'variance': [
        my_arr.var(axis=0).to_list(), my_arr.var(axis=1).to_list(), my_arr.var()
      ],
      # standard deviation
      'standard deviation': [
        my_arr.std(axis=0), my_arr.std(axis=1), my_arr.std()
      ],
      # max
      'max': [
        my_arr.max(axis=0), my_arr.max(axis=1), my_arr.max()
      ],
      # min
      'min': [
        my_arr.min(axis=0), my_arr.min(axis=1), my_arr.min()
      ],
      # sum
      'sum': [
        my_arr.sum(axis=0), my_arr.sum(axis=1), my_arr.sum()
      ]
}

AttributeError: 'numpy.ndarray' object has no attribute 'to_list'

In [24]:
calculations

{'mean': [array([3.66666667, 5.        , 3.        ]),
  array([3.33333333, 4.        , 4.33333333]),
  3.888888888888889],
 'variance': [array([9.55555556, 0.66666667, 8.66666667]),
  array([ 3.55555556, 10.66666667,  6.22222222]),
  6.987654320987654],
 'standard deviation': [array([3.09120617, 0.81649658, 2.94392029]),
  array([1.88561808, 3.26598632, 2.49443826]),
  2.6434171674156266],
 'max': [array([8, 6, 7]), array([6, 8, 7]), 8],
 'min': [array([1, 4, 0]), array([2, 0, 1]), 0],
 'sum': [array([11, 15,  9]), array([10, 12, 13]), 35]}